//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int ID_Account { get; set; }
        public int ID_User { get; set; }
        public int ID_Access_level { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual Access_level Access_level { get; set; }
        public virtual User User { get; set; }
    }
}
