//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost
    {
        public int ID_Cost { get; set; }
        public int ID_Estate { get; set; }
        public decimal Current_cost { get; set; }
        public System.DateTime First_date { get; set; }
        public decimal First_cost { get; set; }
    
        public virtual Estate Estate { get; set; }
    }
}
