//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam2.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int ID_Request { get; set; }
        public int ID_User { get; set; }
        public Nullable<int> ID_Estate { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual Estate Estate { get; set; }
        public virtual User User { get; set; }
    }
}
